---
title: "COVID in Мoscow"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, fig.width=9, fig.height=6, fig.path = "figures/")

```

```{r init, message=FALSE, warning=FALSE}
library(readr)
library(data.table)
library(ggplot2)
library(readxl)
library(readr)

library(stringr)

library(XML)
library(RCurl)
library(forecast)
library(purrr)
library(purrr)

library(strucchange)
library(segmented)

library(xlsx)
```



```{r }
CovidMoscowDB <- read_excel("data/CovidMoscow.xlsx",
col_types = c("numeric", "date", "numeric", "numeric", "numeric"))
CovidMoscowDB <-as.data.table(CovidMoscowDB)
CovidMoscowDB[ ,date:= as.Date(date)]
colnames( CovidMoscowDB) <- c("num", "date", "newCases", "TotalCases", "weekday")
setkey( CovidMoscowDB, date)

source("parse_rospotrebnadzor_pages.R")
CovidMoscowDB.1 <- update_CovidMoscowDB(CovidMoscowDB)
if( dim(CovidMoscowDB.1)[1] > dim(CovidMoscowDB)[1]) {
  #some bug - adds num column all by itself
  write.xlsx(CovidMoscowDB.1[ , mget(colnames(CovidMoscowDB.1)[-1])], file="data/CovidMoscow.xlsx")
  update1 <- setdiff( CovidMoscowDB$date, CovidMoscowDB.1$date)
  
  CovidMoscowDB <- CovidMoscowDB.1
  setkey( CovidMoscowDB, date)
  print( "CovidMoscowDB updated")
  print( update1)

} else {
  print( "CovidMoscowDB was NOT updated")
}

# View(CovidMoscow)
```



```{r}
CovidMoscow <-copy(CovidMoscowDB)
```

```{r}
CovidMoscow <- CovidMoscow[ as.Date(date) >= as.Date("2020/03/18") ]

CovidMoscow[ , br := 0 ]
CovidMoscow[ as.Date(date) >= as.Date("2020/04/02"), br := 1 ]

CovidMoscow[ , days_from_beg := as.Date(date) - min(as.Date(date))]
CovidMoscow[ , days_from_apr2 := as.Date(date) - as.Date("2020/04/02")]

```


##Общий тренд 

```{r}
ggplot( CovidMoscow, aes(x=date,y=newCases))+geom_point()+geom_path()+scale_y_log10()+geom_smooth(aes(color="lowess"), size=1.5)+ggtitle("New daily COVID cases in Moscow (log10 scale)")+geom_path(aes(y=ma(newCases, order=3), color="MA(3)"), size=1)
```


```{r}
ggplot( CovidMoscow, aes(x=date,y=newCases))+geom_point()+geom_path()+geom_smooth()+ggtitle("New daily COVID cases in Moscow")+geom_path(aes(y=ma(newCases, order=3), color="MA(3)"), size=1)
```


##One line
```{r}
lm_msk0 <- lm( log(newCases)~ days_from_beg, data=CovidMoscow)
summary(lm_msk0)
```

##Segmented

```{r}
fit_n_segments <- function(npt, lm_msk0, CovidMoscow) {

  start_psi <- c(13, 30, 45, 48, 55, 67)
  
  if( npt > length(start_psi) ) return(NULL)
  
  options(try.outFile = stdout()) 
  seg <-  try( segmented(lm_msk0, psi=start_psi[1:npt]), silent=TRUE, outFile=stdout())

  while( class(seg)[1] != "segmented" || dim(summary(seg)$psi)[1]<npt || 
  summary(seg)$psi[1] < 10) {
    try( seg <- segmented(lm_msk0, psi=start_psi[1:npt]), 
         silent=TRUE, outFile= stdout())
  }
  return( seg)
}
```


```{r}
plot_npsi_fit <- function( npsi, seg,  CovidMoscow )  { 
  BL_moscow <- broken.line(seg)
  CovidMoscow[ ,`:=`( BLfit = BL_moscow$fit, BLse = BL_moscow$se) ]
  

  gg <- ggplot( CovidMoscow, aes(x=as.Date(date),y=newCases, color="Data"))+
    geom_point()+geom_path()+
    scale_y_log10()+
    geom_path(aes(y=exp(BLfit), color="BL fit" ), size=1)+
    geom_ribbon(aes(ymin=exp(BLfit-2*BLse),ymax=exp(BLfit+2*BLse), color="CI95%"),alpha=0.3)+
    ggtitle(paste0( "New daily COVID cases in Moscow (npsi=", npsi,")"))  +
    scale_color_manual( values=c("Data"="black", "BL fit"="blue", "CI95%"="gray"))+ theme(legend.title = element_blank())

  return(gg)
}
```


```{r}
plot_npsi_resid <- function( npsi, seg) {
  plot(resid(seg), t="l", main=paste0( "Seg log(newCases) residuals (npsi=", npsi, ")"))
  abline(h=0,lty=2)
}
```

```{r}
npsi_max <- 6
seg_fit <- vector( "list", npsi_max)
for( i in 1:npsi_max ) {
  seg_fit[[i]] <- fit_n_segments( i, lm_msk0, CovidMoscow )
  cat(paste0( "\n--------------  N. Breaking points = ", i, " =-------------\n"))
  print( summary(seg_fit[[i]]))
}
```

```{r}
for( i in 1:npsi_max ) {
  gg <- plot_npsi_fit( i, seg_fit[[i]],  CovidMoscow )

  #Продолжение тренда начала апреля
  # if( i > 3 ) {
  #   x0<- c(0:60)
  #   k <- first( which( summary(seg_fit[[i]])$psi[, 2] > 27 )) 
  #   d1<- data.table( x1=as.Date(CovidMoscow[1, date])+x0,
  #                   y0=exp(intercept(seg_fit[[i]])[[1]][[k]] + x0*slope(seg_fit[[i]],
  #                     "days_from_beg")[[1]][k,1]))
  #  gg  <- gg +   geom_path(data=d1, aes(x=as.Date(x1), y=y0), linetype="dotted")
  # } 

  print( gg)
}
```

```{r}
plot_npsi_resid( npsi_max, seg_fit[[npsi_max]])
```

```{r}
for( i in 1:npsi_max ) {

    cat(paste0( "\n--------------  N. Breaking points = ", i, " =-------------\n"))
    cat("Slopes\n")
    print( slope(seg_fit[[i]]))
    cat("Doubling of cases:\n")
    print( log(2)/slope(seg_fit[[i]])$days_from_beg[,1] )
}
```





##Struct change
```{r}
bp1 <- breakpoints(log(newCases)~ days_from_beg, data=CovidMoscow, h=7/CovidMoscow[,.N])
bp1
```

```{r}
ggplot( CovidMoscow, aes(x=date,y=newCases, color="Data"))+geom_point()+geom_path()+   geom_path(aes(y=exp(fitted(bp1)),color="BP"))+scale_y_log10()
```



#Дифференциалы
```{r}
ggplot( CovidMoscow, aes(x=date,y=c(0, diff(log(newCases)))))+geom_point()+geom_path()+geom_smooth()+ggtitle("dlog(New daily COVID cases in Moscow)")
```


```{r}
ggplot( CovidMoscow, aes(x=date,y=log(newCases)-shift(log(newCases), 7)))+geom_point()+geom_path()+geom_smooth()+ggtitle("dlog(New daily COVID cases in Moscow), 7d lag")
```



```{r}
ggplot( CovidMoscow, aes(x=date,y=log(newCases)-shift(log(newCases), 14)))+geom_point()+geom_path()+geom_smooth()+ggtitle("dlog(New daily COVID cases in Moscow), 14d lag")
```


###ARMA errors

```{r}
library(forecast)
d1 <- CovidMoscow[ as.Date(date) >= as.Date("2020/04/01")]
ar1 <- auto.arima( log(d1$newCases), xreg= as.numeric(d1$days_from_beg ))
summary(ar1)
```
```{r}
plot(residuals(ar1), main="ARIMA residuals")
abline(h=0, lty=2)
```



##Apple mobility trends
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
applemobilitytrends <- read_csv("data/applemobilitytrends-2020-05-10.csv")
applemobilitytrends <- as.data.table( applemobilitytrends)

applemobilitytrends <- applemobilitytrends[ region == "Moscow"]

apple_msk <- data.table( date=names(applemobilitytrends)[4:(dim(applemobilitytrends)[2])], v1 = as.numeric(unlist(applemobilitytrends[1,])[-c(1:3)]), 
v2 = as.numeric(unlist(applemobilitytrends[2,])[-c(1:3)]))

names( apple_msk )[2:3] <- c( unlist(applemobilitytrends[1,])[3],
                              unlist(applemobilitytrends[2,])[3])

apple_msk <- na.omit(apple_msk)
```


```{r}
ggplot(apple_msk, aes(x=as.Date(date), y=driving, color="Driving"))+geom_line(size=1)+geom_line(aes(y=walking, color="Walking"),size=1) + ggtitle("Apple Mobility Trends Report - Moscow")+xlab("Date")+ylab("Mobility")
```

```{r}
ggplot(apple_msk[as.Date(date) >= as.Date("2020/03/01")], aes(x=as.Date(date), y=walking, color="Walking"))+geom_line(size=1)+ ggtitle("Apple Mobility Trends Report (Moscow) + \n COVID new cases growth rate")+xlab("Date")+ylab("Mobility, 40*newCases_growth_rate") + 
  geom_line( data=CovidMoscow, aes(x=date,y=40*(log(newCases)-shift(log(newCases), 7)), color="40*diff_7d(log(newCovid))"))
```


##Rolling sum over 2 weeks (aka active cases)
```{r}
CovidMoscow[ , rsum := cumsum(newCases)][ ,rsum := rsum - shift(rsum,12)]

ggplot( CovidMoscow, aes(x=date,y=rsum))+geom_point()+geom_path()+scale_y_log10()+ggtitle("14d sum daily COVID-19 cases in Moscow (aka active cases)")+geom_smooth()

```



