---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r init}
library(readr)
library(data.table)
library(ggplot2)
library(readxl)
library(stringr)

library(XML)
library(RCurl)

```

```{r}
url <- "https://www.worldometers.info/coronavirus/"
world=TRUE
skip_left = 1
skip_right =1

```

```{r}
  doc <- getURL(url)
  
  doc_tables <- readHTMLTable(doc, stringsAsFactors = FALSE) #, elFun = tryAsInteger)

```

```{r}
  if( world ) {
    df1 <- apply( doc_tables$main_table_countries_today, c(1,2), as.character)
  } else{
    df1 <- apply( doc_tables$usa_table_countries_today, c(1,2), as.character)
  }

```

```{r}
  df1 <-  apply( df1, c(2), as.character )

```

```{r}
  df1 <- apply( df1, c(1,2), function(x){ str_replace_all(x, ",", "")})

```


```{r}

  df1 <- as.data.table(df1)
  names(df1) <-  sapply(  names(df1), function(x) { str_replace_all(x, "[^[:alnum:]]", ".")}, USE.NAMES = FALSE)


```

```{r}
  changeCols <- colnames(df1)[(skip_left+1):(dim(df1)[2]-skip_right)]
print("Ok4")

  df1[, (changeCols):= lapply(.SD, function(x){ str_replace_all(x, "[,]", "")}),  .SDcols = changeCols]

```

```{r}
  df1[, (changeCols):= lapply(.SD, function(x){ as.numeric(str_replace_all(x, "[^[0-9]]", ""))}),  .SDcols = changeCols]


```

```{r}
  

```

```{r}
  
#  doc_latest[ <- apply( df1, c(1,2), function(x){ gsub("[,]", "",x)})
print("Ok2")


  df_latest <- df1

```


```{r}
plot_world <- function( df_latest, currdate, max1= 1e10 ) {
  df1 <- df_latest[Country.Other != "World" & Country.Other != "Europe" & Country.Other != "Asia" ]
  gg1 <- ggplot(df1[TotalCases< max1, ], aes(x=TotalCases, y=TotalDeaths+Serious.Critical, color="Data"))+
    geom_point() +
    geom_abline(aes(intercept=0, slope=df1[Country.Other=="USA", (TotalDeaths+Serious.Critical)/TotalCases]))+
    geom_abline(aes(intercept=0, slope=df1[Country.Other=="Italy", (TotalDeaths+Serious.Critical)/TotalCases])) +
    geom_text(data=df1[TotalCases>15000 & TotalCases< max1], aes(x=TotalCases,y=TotalDeaths+Serious.Critical, label=Country.Other ), hjust=-0.1, size=3)+
    ggtitle(paste0("Cases with complications (D+C+S) vs total number of cases ", currdate))+
              guides(colour=guide_legend(title=NULL)) 
  
#  + xlim(0, min(max1, max(df1$TotalCases)))+ylim(0, df1[TotalCases< max1, max(TotalDeaths+Serious.Critical)])
    print(gg1)
}
```

```{r}
i1 <- which( df_latest$Country.Other == "" ) + 2
i2 <- dim( df_latest)[1]
# df_latest[ i1:i2, ]
plot_world( df_latest[ i1:i2], Sys.Date())
```

