---
title: "Worldometer Global Covid data viz"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r init}
library(readr)
library(data.table)
library(ggplot2)
library(readxl)
library(stringr)

library(XML)
library(RCurl)

```


```{r}

Covid_global_0330 <- read_excel("data/Covid_global_0330.xlsx")
Covid_global_0330 <- as.data.table(Covid_global_0330)
```

```{r}
names(Covid_global_0330)<-str_replace_all(names(Covid_global_0330), c(" " = "." , "," = "" ))
data2 <- Covid_global_0330[ TotalCases > 5000 & Country.Other != "World" ]

ggplot(data2, aes(x=TotalCases, y=TotalDeaths+SeriousCritical, color="Data"))+geom_point() +geom_abline(aes(intercept=0, slope=data2[Country.Other=="USA", (TotalDeaths+SeriousCritical)/TotalCases]))+geom_abline(aes(intercept=0, slope=data2[Country.Other=="Italy", (TotalDeaths+SeriousCritical)/TotalCases])) +geom_text(data=data2[TotalCases>15000], aes(x=TotalCases,y=TotalDeaths+SeriousCritical, label=Country.Other ), hjust=-0.1, size=4)+ggtitle("Dangerous cases vs total number of cases 30.03.2020")+ guides(colour=guide_legend(title=NULL))
```

```{r}
read_worldometer <- function( url, world=FALSE, skip_left = 1, skip_right =1) {

  #The only reliable way
  doc <- getURL(url)
  
  doc_tables <- readHTMLTable(doc, stringsAsFactors = FALSE) #, elFun = tryAsInteger)
  
  if( world ) {
    df1 <- apply( doc_tables$main_table_countries_today, c(1,2), as.character)
  } else{
    df1 <- apply( doc_tables$usa_table_countries_today, c(1,2), as.character)
  }

  df1 <-  apply( df1, c(2), as.character )

#  names(df1) <- df1[1,]
#  df1 <-df1[-1, ]
  
  df1 <- apply( df1, c(1,2), function(x){ str_replace_all(x, ",", "")})
#View(df1)
#  df_latest[,-1] <-  apply( df_latest[,-1], c(2), as.integer )

  df1 <- as.data.table(df1)
  changeCols <- colnames(df1)[(skip_left+1):(dim(df1)[2]-skip_right)]
#print(changeCols)

  df1[, (changeCols):= lapply(.SD, function(x){ str_replace_all(x, "[,]", "")}),  .SDcols = changeCols]
  
#  doc_latest[ <- apply( df1, c(1,2), function(x){ gsub("[,]", "",x)})

  df1[, (changeCols):= lapply(.SD, function(x){ as.numeric(str_replace_all(x, "[^[0-9]]", ""))}),  .SDcols = changeCols]
  
  names(df1) <-  sapply(  names(df1), function(x) { str_replace_all(x, "[^[:alnum:]]", ".")}, USE.NAMES = FALSE)

  return(df1)  
}
```

```{r}
  cached_date <- "2020406"
  from_cache <-FALSE
  
  if(!from_cache ) {
    #Read latest data
    df_latest <- read_worldometer( "https://www.worldometers.info/coronavirus/", 
                                   world=TRUE, 2, 1)
    
    # url <- "https://www.worldometers.info/coronavirus/#countries"
  
    save(df_latest, file=paste0(Sys.Date(), "_df_latest.RData"))
    plot_date <- Sys.Date()
  
  } else {
    load(file=paste0(cached_date, "_df_latest.RData"))
    plot_date <- cached_date()
  }
```


```{r}
plot_world <- function( df_latest, currdate, max1= 1e10 ) {
  df1 <- df_latest[Country.Other != "World" & Country.Other != "Europe" & Country.Other != "Asia" ]
  gg1 <- ggplot(df1[TotalCases< max1, ], aes(x=TotalCases, y=TotalDeaths+Serious.Critical, color="Data"))+
    geom_point() +
    geom_abline(aes(intercept=0, slope=df1[Country.Other=="USA", (TotalDeaths+Serious.Critical)/TotalCases]))+
    geom_abline(aes(intercept=0, slope=df1[Country.Other=="Italy", (TotalDeaths+Serious.Critical)/TotalCases])) +
    geom_text(data=df1[TotalCases>15000 & TotalCases< max1], aes(x=TotalCases,y=TotalDeaths+Serious.Critical, label=Country.Other ), hjust=-0.1, size=3)+
    ggtitle(paste0("Cases with complications (D+C+S) vs total number of cases ", currdate))+
              guides(colour=guide_legend(title=NULL)) 
  
#  + xlim(0, min(max1, max(df1$TotalCases)))+ylim(0, df1[TotalCases< max1, max(TotalDeaths+Serious.Critical)])
    print(gg1)
}
```



```{r}
i1 <- which( df_latest$Country.Other == "" ) + 2
i2 <- dim( df_latest)[1]
# df_latest[ i1:i2, ]
plot_world( df_latest[ i1:i2], Sys.Date())
```


```{r}
plot_world( df_latest[ i1:i2], Sys.Date(), max1=250000)

```


```{r}
plot_world( df_latest[ i1:i2], Sys.Date(), max1=100000)

```

```{r}
plot_world( df_latest[ i1:i2], Sys.Date())
```

```{r}
ggplot(df_latest[i1:i2], aes(x=TotalCases, y=TotalDeaths+Serious.Critical, color="Data"))+geom_point()+geom_text(data=df_latest[TotalCases>5000], aes(x=TotalCases,y=TotalDeaths+Serious.Critical, label=Country.Other ), hjust=-0.1, size=3)+ggtitle("Complicated cases vs total number of cases 06.04.2020")+ guides(colour=guide_legend(title=NULL))+scale_x_log10()+scale_y_log10()

```





```{r}
# names(df_latest)
df_latest[ , TestPosRatio := TotalCases/TotalTests ]

dfl1 <- df_latest[TotalCases > 5000 ]
ggplot(dfl1, aes(x=Tests.1M.pop/1e6, y=TestPosRatio, color="Data"))+geom_point()+geom_text(data=dfl1, aes(x=Tests.1M.pop/1e6,y=TestPosRatio, label=Country.Other  ), hjust=-0.1, size=3)+ggtitle(paste0("Positive tests share vs tests per citizen ",Sys.Date()))+ guides(colour=guide_legend(title=NULL))+xlab("Tests per citizen") + ylab("Share of positives tests") + xlim(0,0.05)


#+scale_x_log10()+scale_y_log10()

```
```{r}
ggplot(dfl1, aes(x=Tests.1M.pop/1e6, y=`Tot.Cases.1M.pop`/1e6, color="Data"))+geom_point()+geom_text(data=dfl1, aes(x=Tests.1M.pop/1e6,y=`Tot.Cases.1M.pop`/1e6, label=Country.Other  ), hjust=-0.1, size=3)+ggtitle(paste0("Positive test share vs tests per citizen ", Sys.Date()))+ guides(colour=guide_legend(title=NULL))+xlab("Tests per citizen") + ylab("Positives per citizen")

```



